"""initial_schema

Revision ID: 4c7469824631
Revises: 
Create Date: 2026-04-23 03:12:37.370290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c7469824631'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.Enum('USER_TOKEN_WALLET', 'TOKEN_ISSUANCE', 'USER_USD_WALLET', 'CONVERSION_POOL', 'FEE_PAYABLE', 'DREAMLAND_FEE_EXP', name='accountcode'), nullable=False),
    sa.Column('account_type', sa.Enum('ASSET', 'LIABILITY', 'EQUITY', 'REVENUE', 'EXPENSE', name='accounttype'), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_code'), 'accounts', ['code'], unique=False)
    op.create_index(op.f('ix_accounts_user_id'), 'accounts', ['user_id'], unique=False)
    op.create_table('conversion_jobs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('hour_bucket', sa.DateTime(timezone=True), nullable=False, comment='Floor-to-hour UTC timestamp, e.g. 2024-11-01T14:00:00Z'),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'RETRYING', name='jobstatus'), nullable=False),
    sa.Column('token_rate_usd', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('entries_processed', sa.Integer(), nullable=False),
    sa.Column('usd_total', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('fee_total', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hour_bucket')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False, comment='ID from upstream identity provider (Auth0, Cognito, etc.)'),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('timezone', sa.String(length=60), nullable=False, comment='IANA timezone string — used for daily-cap boundary'),
    sa.Column('region', sa.String(length=30), nullable=False, comment='Data residency region: eu | us | apac | global'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_external_id'), 'users', ['external_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('idempotency_keys',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('request_path', sa.String(length=200), nullable=False),
    sa.Column('request_params', sa.String(length=2000), nullable=False),
    sa.Column('response_code', sa.String(length=10), nullable=True),
    sa.Column('response_body', sa.String(length=4000), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_idempotency_user_key', 'idempotency_keys', ['user_id', 'key'], unique=True)
    op.create_table('token_ledger',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False, comment='Groups the debit+credit pair. SUM(amount) per txn_id must = 0'),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('entry_type', sa.Enum('DEBIT', 'CREDIT', name='entrytype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=8), nullable=False, comment='Positive for DEBIT, negative for CREDIT. NEVER FLOAT.'),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True, comment='Client-supplied key to prevent duplicate win events'),
    sa.Column('won_at', sa.DateTime(timezone=True), nullable=False, comment='When the user actually won the tokens (stored as UTC)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_converted', sa.Boolean(), nullable=False, comment='True once the hourly job has converted this entry to USD'),
    sa.Column('conversion_job_id', sa.UUID(), nullable=True),
    sa.CheckConstraint("(entry_type = 'DEBIT' AND amount > 0) OR (entry_type = 'CREDIT' AND amount < 0)", name='chk_token_amount_sign'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['conversion_job_id'], ['conversion_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_ledger_account_id'), 'token_ledger', ['account_id'], unique=False)
    op.create_index(op.f('ix_token_ledger_conversion_job_id'), 'token_ledger', ['conversion_job_id'], unique=False)
    op.create_index(op.f('ix_token_ledger_idempotency_key'), 'token_ledger', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_token_ledger_is_converted'), 'token_ledger', ['is_converted'], unique=False)
    op.create_index(op.f('ix_token_ledger_transaction_id'), 'token_ledger', ['transaction_id'], unique=False)
    op.create_index('uq_token_ledger_idempotency', 'token_ledger', ['account_id', 'idempotency_key'], unique=True, postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.create_table('usd_ledger',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('entry_type', sa.Enum('DEBIT', 'CREDIT', name='entrytype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('source_token_transaction_id', sa.UUID(), nullable=True, comment='Cross-ref: which token_ledger transaction triggered this'),
    sa.Column('conversion_job_id', sa.UUID(), nullable=True),
    sa.Column('converted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(entry_type = 'DEBIT' AND amount > 0) OR (entry_type = 'CREDIT' AND amount < 0)", name='chk_usd_amount_sign'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['conversion_job_id'], ['conversion_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usd_ledger_account_id'), 'usd_ledger', ['account_id'], unique=False)
    op.create_index(op.f('ix_usd_ledger_conversion_job_id'), 'usd_ledger', ['conversion_job_id'], unique=False)
    op.create_index(op.f('ix_usd_ledger_source_token_transaction_id'), 'usd_ledger', ['source_token_transaction_id'], unique=False)
    op.create_index(op.f('ix_usd_ledger_transaction_id'), 'usd_ledger', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usd_ledger_transaction_id'), table_name='usd_ledger')
    op.drop_index(op.f('ix_usd_ledger_source_token_transaction_id'), table_name='usd_ledger')
    op.drop_index(op.f('ix_usd_ledger_conversion_job_id'), table_name='usd_ledger')
    op.drop_index(op.f('ix_usd_ledger_account_id'), table_name='usd_ledger')
    op.drop_table('usd_ledger')
    op.drop_index('uq_token_ledger_idempotency', table_name='token_ledger', postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.drop_index(op.f('ix_token_ledger_transaction_id'), table_name='token_ledger')
    op.drop_index(op.f('ix_token_ledger_is_converted'), table_name='token_ledger')
    op.drop_index(op.f('ix_token_ledger_idempotency_key'), table_name='token_ledger')
    op.drop_index(op.f('ix_token_ledger_conversion_job_id'), table_name='token_ledger')
    op.drop_index(op.f('ix_token_ledger_account_id'), table_name='token_ledger')
    op.drop_table('token_ledger')
    op.drop_index('uq_idempotency_user_key', table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_external_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('conversion_jobs')
    op.drop_index(op.f('ix_accounts_user_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_code'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###